import = ["./themes/themes/tokyo_night.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
