#!/bin/sh
alias l='ls -G'
alias la='ls -aG'
alias lsa='ls -aG'
alias ll='ls -lhG'
alias lla='ls -alhG'
alias ta='tmux attach'
alias im='vim'
alias vimrc='vim ~/.vim/vimrc'
alias :q='exit'

if [[ $(uname) == *Darwin* ]] # Mac OS X
then
    alias ctags="`brew --prefix`/bin/ctags"
fi

# jwt.show log for datam.at
alias jwtlog='sudo bash zcat -f /var/log/nginx/jwt.show.access.log* | goaccess'
