export PATH="/home/tmadsen/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
export ASPNETCORE_ENVIRONMENT=localhost

case `uname` in
  Darwin)
    export DOTNET_ROOT=/usr/local/share/dotnet
  ;;
esac

# source "$HOME/.cargo/env"
