# export PATH="/usr/local/nvim-macos/bin:/home/tmadsen/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
export PATH="~/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
export PATH="~/.local/share/bob/nvim-bin:$PATH"
export PATH="~/.yarn/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"
export PATH="~/go/bin:$PATH"
export PATH=~/.npm-global/bin:$PATH

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/tmadsen/.lmstudio/bin"
# End of LM Studio CLI section


# export PATH="$(yarn global bin):$PATH"

export XDG_CONFIG_HOME="$HOME/.config"

if uname -a | grep -q 'microsoft'; then
    export ASPNETCORE_ENVIRONMENT=localhost-wsl
else
    export ASPNETCORE_ENVIRONMENT=localhost
fi

case `uname` in
  Darwin)
    export DOTNET_ROOT=/usr/local/share/dotnet
  ;;
esac

