# User paths (highest priority)
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/share/bob/nvim-bin"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.npm-global/bin"

# System paths
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local/mysql/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"
export PATH="$PATH:/usr/local/lib/ruby/gems/2.6.0/bin"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/tmadsen/.lmstudio/bin"
# End of LM Studio CLI section


# export PATH="$(yarn global bin):$PATH"

export XDG_CONFIG_HOME="$HOME/.config"

if uname -a | grep -q 'microsoft'; then
    export ASPNETCORE_ENVIRONMENT=localhost-wsl
else
    export ASPNETCORE_ENVIRONMENT=localhost
fi

case `uname` in
  Darwin)
    export DOTNET_ROOT=/usr/local/share/dotnet
  ;;
esac

