# Path to the directory of the zshrc file. This path is filled in install.sh
# initially, and then by git filters.
zsh_config_dir=/Users/tmadsen/projects/dotfiles/zsh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

setopt prompt_subst
autoload -U colors && colors
autoload -U compinit && compinit

source $zsh_config_dir/git-prompt.sh
local gitval='%{$fg[green]%}$(__git_ps1 "(%s)")'

prompt="%{$fg[yellow]%}%n@%m %{$fg[blue]%}%~ ${gitval}
%{$fg[red]%}$ %{$reset_color%}"

# Aliases
alias l='ls -lhoG'
alias la='ls -laho'
alias ls='ls -G'
alias lsa='ls -Ga'
alias s='cd ..'
alias venv='source venv/bin/activate'
alias mkvenv='virtualenv venv'
alias ccat='pygmentize -O style=fruity,linenos=1 -f console256 -g'
alias im='vim'
alias vim='mvim -v'
alias ctags="`brew --prefix`/bin/ctags"

# More completions.
fpath=($zsh_config_dir/zsh-completions/src $fpath)
