# Path to the directory of the zshrc file. This path is filled in install.sh
# initially, and then by git filters.
zsh_config_dir=/Users/tmadsen/projects/dotfiles/zsh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

setopt prompt_subst
autoload -U colors && colors
autoload -U compinit && compinit

source $zsh_config_dir/git-prompt.sh
local gitval='%{$fg[green]%}$(__git_ps1 "(%s)")'

prompt="%{$fg[yellow]%}%n@%m %{$fg[blue]%}%~ ${gitval}
%{$fg[red]%}$ %{$reset_color%}"

# Aliases
alias l='ls -lhoG'
alias la='ls -laho'
alias ls='ls -G'
alias lsa='ls -Ga'

if [[ $(uname) == *CYGWIN* ]]
then
    alias l='ls --color -lho'
    alias la='ls --color -laho'
    alias ls='ls --color -G'
    alias lsa='ls --color -Ga'
fi

alias s='cd ..'
alias venv='source venv/bin/activate'
alias mkvenv='virtualenv venv'
alias ccat='pygmentize -O style=fruity,linenos=1 -f console256 -g'
alias im='vim'

if [[ $(uname) == *Darwin* ]] # Mac OS X
then
    alias vim='mvim -v'
    alias ctags="`brew --prefix`/bin/ctags"
fi

# More completions.
fpath=($zsh_config_dir/zsh-completions/src $fpath)

# case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _expand _complete _ignored

# generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, page it!
zstyle ':completion:*:default' list-prompt '%S%M matches%s'

# Don't prompt for a huge list, menu it!
zstyle ':completion:*:default' menu 'select=0'

# Have the newer files last so I see them first
zstyle ':completion:*' file-sort modification reverse

