export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM="xterm-256color"
fpath=( "$HOME/.utilities" $fpath )
fpath=( ~/.zsh/completion $fpath)

setopt inc_append_history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

tabs -2

setopt prompt_subst
autoload -U colors && colors
autoload -U compinit && compinit
autoload -U select-word-style
select-word-style bash
autoload -U promptinit; promptinit
prompt pure

source ~/.aliases
source ~/.ssh-start.sh

# case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _expand _complete _ignored

# generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, page it.
zstyle ':completion:*:default' list-prompt '%S%M matches%s'

# Don't prompt for a huge list, menu it.
zstyle ':completion:*:default' menu 'select=0'

# Shift-tab goes back in the menu.
bindkey '^[[Z' reverse-menu-complete

# Have the newer files last so I see them first
zstyle ':completion:*' file-sort modification reverse

# Better directory completion
zstyle ':completion:*' special-dirs true

zmodload zsh/complist

function settitle() {
	echo -ne "\e]0;$1\a"
}

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
# actually, for me, this changes the pure prompt cursor from a
# right-pointing arrow to a left-pointing arrow which I thought
# was a nice accident so I haven't changed it :)
zle-keymap-select () {
    if [ "$TERM" = "xterm-256color" ]; then
        if [ $KEYMAP = vicmd ]; then
            # the command mode for vi
            echo -ne "\e[2 q"
        else
            # the insert mode for vi
            echo -ne "\e[4 q"
        fi
    fi
}

# Use lf to switch directories and bind it to ctrl-o
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

PATH="/home/tmadsen/.yarn/bin:/usr/lib/:/usr/local/lib${PATH+:}${PATH}"; export PATH;
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"
export PATH="/home/tmadsen/go/bin:$PATH"
export FZF_COMPLETION_OPTS='-e'
export FZF_DEFAULT_COMMAND='ag --ignore-dir={bin,obj,node_modules} -g ""'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Load zsh-syntax-highlighting; should be last.
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
