export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM="xterm-256color"
source ~/.aliases
source ~/.ssh-start.sh

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.history

tabs -2

export KEYTIMEOUT=1
